services:
  top-api:
    image: ghcr.io/ascender11/app:master
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
